name: Maureen Callahan
favicon: null
layout_spectrum: 0.6681848538573831
typography_spectrum: 0.4188678013160825
title: Strategist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f2f2f4'
    - '#c4ccd7'
    - '#7c9ec1'
    - '#526060'
  brandStrength: 0.11712593911215663
  lightness: 0.6302913876716048
  saturation: 1
  rhythmicContrast: 0.3881501234136522
purpose: []
